name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: lucas-baggio
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          config_padding: 10%
          optimize: svg
          filename: github-metrics.svg

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_analysis_timeout: 15

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_repositories: yes
          plugin_repositories_featured: lucas-baggio/devquest, lucas-baggio/evolucao
